#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source_dir=$1

if [ -z "${source_dir}" ]; then
  echo "usage: $0 <path/to/source>" >&2
  exit 1
fi

mkdir -p "${source_dir}"

source $(dirname $0)/common.sh

if [[ "${operation}" == "silence" ]]; then
	if [[ -z "${matchers}" ]]; then
	  echo >&2 "must specify 'matchers' parameter"
	  exit 1
	fi

	silence_id=$(amtool --alertmanager.url ${url} \
                      silence add \
                      --author "${creator}" \
                      --comment "${comments}" \
                      --expires "${expires}" \
                      ${matchers})

	amtool --alertmanager.url ${url} \
	       --output json \
	       silence query | \
	       jq -e ".[] | select(.id == \"${silence_id}\") | {
	         version: { ref: .id },
	         metadata: [
	           { name: \"created_by\", value: .createdBy },
               { name: \"comment\", value: .comment },
	           { name: \"starts_at\", value: .startsAt },
	           { name: \"ends_at\", value: .endsAt },
               { name: \"updated_at\", value: .updatedAt }
	         ]
	        }" >&3
elif [[ "${operation}" == "expire" ]]; then
	silence=$(jq -r '.params.silence // ""' < ${payload})
	if [[ -z "${silence}" ]]; then
	  echo >&2 "must specify 'silence' parameter"
	  exit 1
	fi

	silence_id=$(cat "${source_dir}/${silence}/silence")
	amtool --alertmanager.url ${url} \
	       silence expire "${silence_id}"

	amtool --alertmanager.url ${url} \
	       --output json \
	       silence query --expired | \
	       jq -e ".[] | select(.id == \"${silence_id}\") | {
	         version: { ref: .id },
	         metadata: [
	           { name: \"created_by\", value: .createdBy },
	           { name: \"comment\", value: .comment },
	           { name: \"starts_at\", value: .startsAt },
	           { name: \"ends_at\", value: .endsAt },
               { name: \"updated_at\", value: .updatedAt }
	         ]
	        }" >&3
else
	echo >&2 "invalid operation parameter '${operation}' - should be 'silence' or 'expire'"
	exit 1
fi

exit 0
